services:
  webserver:
    image: "nginx:stable-alpine"
    working_dir: /app
    volumes:
      - .:/app
      - ./config/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - php_fpm_socket:/run/php
    ports:
      - 29300:80
  php-fpm:
    build: .
    working_dir: /app
    volumes:
      - .:/app
      - ./config/php-fpm/php-ini-overrides.ini:/etc/php/8.3/fpm/conf.d/99-overrides.ini
      - ./config/php-fpm/z-overrides.conf:/etc/php/8.3/fpm/pool.d/z-overrides.conf
      - php_fpm_socket:/run/php

volumes:
  php_fpm_socket: