services:
  nginx:
    build:
      context: .
      dockerfile: Dockerfile.nginx
    ports:
      - 29300:80
  php-fpm:
    build:
      context: .
      dockerfile: Dockerfile.php-fpm
    volumes:
      - ./cache:/var/www/html/cache
      - ./storage:/var/www/html/storage
